dependencies {
    implementation project(':model')
    implementation project(':security')
    implementation project(':log')
    implementation project(':utils')
    implementation 'org.springframework:spring-context'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.boot:spring-boot-starter-security'
}
