server:
  port: 8080
spring:
  application:
    name: "crediYaSolicitudes"
  devtools:
    add-properties: false
  profiles:
    include: null
adapters:
  r2dbc:
    host: "localhost"
    port: 3306
    database: "solicitudes"
    username: "app_user"
    password: "juan*201"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
