##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: crediYaSolicitudes
  devtools:
    add-properties: false
  profiles:
    include:

adapters:
  r2dbc:
    host: localhost
    port: 3306
    database: mydb
    user: test
    password: test

